name: CI/CD
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          envkey_VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}

      - name: Build
        run: npm run build-prod

      #      - name: Test
      #        run: npm run test:unit

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        if: github.event_name == 'push'
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          source: './dist/*'
          target: '/var/www/circuitcratft/html/'
